package com.sample
 
// import com.sample.DroolsTest.Message;
import java.util.ArrayList;

declare enum statusType
HELLO(0),GOODBYE(1);
	type_: int
end

declare Question
	question: String
	answers: ArrayList
	result: String
end

rule "Init"
	when
	then
		ArrayList<String> options = new ArrayList();
		options.add("Movie");
		options.add("TV Show");
		String question = "Movie or TV Show?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

// ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

rule "Movie"
	when
		exists Question(question == "Movie or TV Show?", result == "Movie");	
	then
		ArrayList<String> options = new ArrayList();
		options.add("Timeless Classics");
		options.add("Action");
		options.add("Documentaries");
		options.add("Comedy");
		options.add("Drama");
		options.add("Horror");
		String question = "What genre?"; 
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

// ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

rule "Timeless Classics"
	when
		exists Question(question == "What genre?", result == "Timeless Classics")
	then
		ArrayList<String> options = new ArrayList();
		options.add("Scientists create a cannon to send them to the moon");
		options.add("A lawyer defends an innocent blac man in 1930's south");
		options.add("A German expressionist film where an upper class man leads the lower class in revolt");
		String question = "Which topic?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;


rule "Cannon to moon"
	when
		exists Question(question == "Which topic?", result == "Scientists create a cannon to send them to the moon");
	then
		GuiPopup p1 = new GuiPopup("You should watch A Trip to the Moon", new ArrayList<String>());
		p1.ask();
end;

rule "Lawyer"
	when
		exists Question(question == "Which topic?", result == "A lawyer defends an innocent blac man in 1930's south");
	then
		GuiPopup p1 = new GuiPopup("You should watch To Kill a Mockingbird", new ArrayList<String>());
		p1.ask();
end;

rule "Metropolis"
	when
		exists Question(question == "Which topic?", result == "A German expressionist film where an upper class man leads the lower class in revolt");
	then
		GuiPopup p1 = new GuiPopup("You should watch Matropolis", new ArrayList<String>());
		p1.ask();
end;

// ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

rule "Action Movie"
	when
		exists Question(question == "Movie or TV Show?", result == "Movie");	
		exists Question(question == "What genre?", result == "Action")
	then
		ArrayList<String> options = new ArrayList();
		options.add("Martial arts");
		options.add("Serious");
		options.add("Goofy");
		String question = "What type?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "Martial arts"
	when
		exists Question(question == "Movie or TV Show?", result == "Movie");	
		exists Question(question == "What type?", result == "Martial arts")
	then
		ArrayList<String> options = new ArrayList();
		options.add("Realistic");
		options.add("Tarantino directed revenge movie");
		options.add("Special effects out the wazoo");
		String question = "Which topic?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "Way of dragon"
	when
		exists Question(question == "Which topic?", result == "Realistic");
	then
		GuiPopup p1 = new GuiPopup("You should watch Way of the Dragon", new ArrayList<String>());
		p1.ask();
end;

rule "Kill Bill"
	when
		exists Question(question == "Which topic?", result == "Tarantino directed revenge movie");
	then
		GuiPopup p1 = new GuiPopup("You should watch Kill Bill Vol.1 and Kill Bill Vol.2", new ArrayList<String>());
		p1.ask();
end;

rule "Five venoms"
	when
		exists Question(question == "Which topic?", result == "Special effects out the wazoo");
	then
		GuiPopup p1 = new GuiPopup("You should watch The Five Venoms", new ArrayList<String>());
		p1.ask();
end;


rule "Serious Movie"
	when
		exists Question(question == "Movie or TV Show?", result == "Movie");	
		exists Question(question == "What type?", result == "Serious")
	then
		ArrayList<String> options = new ArrayList();
		options.add("Comic book based");
		options.add("Sci-fi");
		String question = "What subtype?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "Comic book based Movie"
	when
		exists Question(question == "What subtype?", result == "Comic book based");	 	
	then
		ArrayList<String> options = new ArrayList();
		options.add("Film Noir");
		options.add("Ron Perlman in a shit ton of makeup");
		String question = "Which topic?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));	
end;

rule "Hellboy"
	when 
		exists Question(question == "Which topic?", result == "Ron Perlman in a shit ton of makeup");	 	
	then
		GuiPopup p1 = new GuiPopup("You should watch Hellboy", new ArrayList<String>());
		p1.ask();
end;

rule "Sin city"
	when
 		exists Question(question == "Which topic?", result == "Film Noir");	 	
	then
		GuiPopup p1 = new GuiPopup("You should watch Sin City", new ArrayList<String>());
		p1.ask();
end;

rule "Sci fi movie"
	when
		exists Question(question == "What subtype?", result == "Sci-fi");	 	
	then
		ArrayList<String> options = new ArrayList();
		options.add("Cyberpunk cop in a huge city");
		options.add("Asteroid apocalypse");
		String question = "Which topic?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));	
end;

rule "Cyberpunk"
	when
 		exists Question(question == "Which topic?", result == "Cyberpunk cop in a huge city");	 	
	then
		GuiPopup p1 = new GuiPopup("You should watch Judge Dredd", new ArrayList<String>());
		p1.ask();
end;

rule "Asteroid apocalypse"
	when
 		exists Question(question == "Which topic?", result == "Asteroid apocalypse");	 	
	then
		GuiPopup p1 = new GuiPopup("You should watch Armageddon", new ArrayList<String>());
		p1.ask();
end;


rule "Goofy Movie"
	when
		exists Question(question == "Movie or TV Show?", result == "Movie");	
		exists Question(question == "What type?", result == "Goofy")
	then
		ArrayList<String> options = new ArrayList();
		options.add("British");
		options.add("Not British");
		String question = "What subtype?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "Hot fuzz"
	when
		exists Question(question == "Movie or TV Show?", result == "Movie");	
 		exists Question(question == "What subtype?", result == "British");	 	
	then
		GuiPopup p1 = new GuiPopup("You should watch Hot Fuzz", new ArrayList<String>());
		p1.ask();
end;

rule "Not British Movie"
	when
		exists Question(question == "Movie or TV Show?", result == "Movie");	
		exists Question(question == "What subtype?", result == "British");	 	
	then
		ArrayList<String> options = new ArrayList();
		options.add("Homage to 80's");
		options.add("Actually from the 80's");
		options.add("Tarantino directed movie about people killing Nazis");
		String question = "Which topic?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));	
end;

rule "Kung fury"
	when
		exists Question(question == "Which topic?", result == "Homage to 80's");
	then
		GuiPopup p1 = new GuiPopup("You should watch Kung Fury", new ArrayList<String>());
		p1.ask();
end;

rule "Big trouble in China"
	when
		exists Question(question == "Which topic?", result == "Actually from the 80's");
	then
		GuiPopup p1 = new GuiPopup("You should watch Big Trouble in Little China", new ArrayList<String>());
		p1.ask();
end;

rule "Inglorious Bastards"
	when
		exists Question(question == "Which topic?", result == "Tarantino directed movie about people killing Nazis");
	then
		GuiPopup p1 = new GuiPopup("You should watch Inglorious Bastards", new ArrayList<String>());
		p1.ask();
end;

// ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

rule "Documentaries"
	when
		exists Question(question == "What genre?", result == "Documentaries")
	then
		ArrayList<String> options = new ArrayList();
		options.add("An inside look into the amateur porn industry");
		options.add("Noam Chromsy looks at wealth inequality in America");
		options.add("A story of drug dealers in 1980's Florida");
		options.add("A study of German Expressionist cinema and fascism");
		String question = "Which topic?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "Porn"
	when
		exists Question(question == "Which topic?", result == "An inside look into the amateur porn industry");
	then
		GuiPopup p1 = new GuiPopup("You should watch Hot Girls Wanted", new ArrayList<String>());
		p1.ask();
end;

rule "Requiem"
	when
		exists Question(question == "Which topic?", result == "Noam Chromsy looks at wealth inequality in America");
	then
		GuiPopup p1 = new GuiPopup("You should watch Requiem for the American Dream", new ArrayList<String>());
		p1.ask();
end; 

rule "Drugs"
	when
		exists Question(question == "Which topic?", result == "A story of drug dealers in 1980's Florida");
	then
		GuiPopup p1 = new GuiPopup("You should watch Cocaine Cowboys", new ArrayList<String>());
		p1.ask();
end;

rule "German cinema"
	when
		exists Question(question == "Which topic?", result == "A study of German Expressionist cinema and fascism");
	then
		GuiPopup p1 = new GuiPopup("You should watch From Caligari to Hitler", new ArrayList<String>());
		p1.ask();
end;

// ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

rule "Comedy"
	when
		exists Question(question == "What genre?", result == "Comedy")
	then
		ArrayList<String> options = new ArrayList();
		options.add("Coen Brothers");
		options.add("Tarantino");
		options.add("Animated");
		String question = "What type?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "Coen Brothers"
	when
		exists Question(question == "What type?", result == "Coen Brothers")
	then
		ArrayList<String> options = new ArrayList();
		options.add("Greatest thing to happen to this earth. Go buy it on Amazon");
		options.add("The Odyssey set in the depression era south");
		options.add("Minesotan banker tries to ransom his own wife");
		String question = "Choose the description";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "Lebowski"
	when
		exists Question(question == "Choose the description", result == "Greatest thing to happen to this earth. Go buy it on Amazon")
	then
		GuiPopup p1 = new GuiPopup("You should watch The Big Lebowski", new ArrayList());
		p1.ask();
end;

rule "Oh Brother, Where Art Thou"
	when
		exists Question(question == "Choose the description", result == "The Odyssey set in the depression era south");
	then
		GuiPopup p1 = new GuiPopup("You should watch Oh Brother, Where Art Thou", new ArrayList());
		p1.ask();
end;

rule "Fargo"
	when
		exists Question(question == "Choose the description", result == "Minesotan banker tries to ransom his own wife")
	then
		GuiPopup p1 = new GuiPopup("You should watch Fargo", new ArrayList());
		p1.ask();
end;

rule "Tarantino"
	when
		exists Question(question == "What type?", result == "Tarantino")
	then
		ArrayList<String> options = new ArrayList();
		options.add("Non-linear story about gangsters");
		String question = "What story?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "Pulp Fiction"
	when
		exists Question(question == "What story?", result == "Non-linear story about gangsters")
	then
		GuiPopup p1 = new GuiPopup("You should watch Pulp Fiction", new ArrayList());
		p1.ask();
end;

rule "Animated"
	when
		exists Question(question == "What type?", result == "Animated")
	then
		ArrayList<String> options = new ArrayList();
		options.add("Adorable and underrated");
		options.add("Semi-funny trash");
		String question = "Which type?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "Home"
	when
		exists Question(question == "Which type?", result == "Adorable and underrated")
	then
		GuiPopup p1 = new GuiPopup("You should watch Home", new ArrayList());
		p1.ask();
end;

rule "South Park"
	when
		exists Question(question == "Which type?", result == "Semi-funny trash")
	then
		GuiPopup p1 = new GuiPopup("You should watch South Park: Bigger, Longer and Uncut", new ArrayList());
		p1.ask();
end;

// ---------------------------------------------------------------------------------------------------------------------------------------------

rule "Drama Movie"
	when
		exists Question(question == "Movie or TV Show?", result == "Movie");
		exists Question(question == "What genre?", result == "Drama");
	then
		ArrayList<String> options = new ArrayList();
		options.add("Neo-Noir");
		options.add("Cute");
		String question = "What type?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "Neo-Noir"
	when
		exists Question(question == "What type?", result == "Neo-Noir")
	then
		ArrayList<String> options = new ArrayList();
		options.add("Kevin Specey telays his story of a robbery gone south");
		options.add("Iran's first vampier/ganster/western/horror movie");
		options.add("Christopher Nolan directed movie about stalkers");
		String question = "Which topic?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "The Usual Suspect"
	when
		exists Question(question == "Which topic?", result == "Kevin Specey telays his story of a robbery gone south")
	then
		GuiPopup p1 = new GuiPopup("You should watch The Usual Suspect", new ArrayList());
		p1.ask();
end;

rule "A Girl Walks Home Alone at Night"
	when
		exists Question(question == "Which topic?", result == "Iran's first vampier/ganster/western/horror movie")
	then
		GuiPopup p1 = new GuiPopup("You should watch A Girl Walks Home Alone at Night", new ArrayList());
		p1.ask();
end;

rule "Following"
	when
		exists Question(question == "Which topic?", result == "Christopher Nolan directed movie about stalkers")
	then
		GuiPopup p1 = new GuiPopup("You should watch Following", new ArrayList());
		p1.ask();
end;

rule "Cute"
	when
		exists Question(question == "What type?", result == "Cute")
	then
		ArrayList<String> options = new ArrayList();
		options.add("Teenager starts seeing his dead brother");
		options.add("French movie about a girl's first lesbian relationship");
		options.add("Wes Anderson movie about two kids running away from home");
		String question = "Which topic?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "Charlie St. Cloud"
	when
		exists Question(question == "Which topic?", result == "Teenager starts seeing his dead brother")
	then
		GuiPopup p1 = new GuiPopup("You should watch Charlie St. Cloud", new ArrayList());
		p1.ask();
end;

rule "Blue is the Warmest Color"
	when
		exists Question(question == "Which topic?", result == "French movie about a girl's first lesbian relationship")
	then
		GuiPopup p1 = new GuiPopup("You should watch Blue is the Warmest Color", new ArrayList());
		p1.ask();
end;

rule "Moonrise Kingdom"
	when
		exists Question(question == "Which topic?", result == "Wes Anderson movie about two kids running away from home")
	then
		GuiPopup p1 = new GuiPopup("You should watch Moonrise Kingdom", new ArrayList());
		p1.ask();
end;

// ---------------------------------------------------------------------------------------------------------------------------------------------

rule "Horror Movie"
	when
		exists Question(question == "What genre?", result == "Horror")
	then
		ArrayList<String> options = new ArrayList();
		options.add("Cult Horror");
		options.add("Classic Horror");
		options.add("Contemporary Horror");		
		String question = "What type?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "Cult Horror"
	when
		exists Question(question == "What type?", result == "Cult Horror")
	then
		ArrayList<String> options = new ArrayList();
		options.add("Extremely gory movie about sadists from another dimension");
		options.add("A haunted house tortures its family");
		String question = "Which topic?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "Hellraiser"
	when
		exists Question(question == "Which topic?", result == "Extremely gory movie about sadists from another dimension")
	then
		GuiPopup p1 = new GuiPopup("You should watch Hellraiser", new ArrayList());
		p1.ask();
end;

rule "Amityville"
	when
		exists Question(question == "Which topic?", result == "A haunted house tortures its family")
	then
		GuiPopup p1 = new GuiPopup("You should watch The Amityville Horror", new ArrayList());
		p1.ask();
end;

rule "Classic Horror"
	when
		exists Question(question == "What type?", result == "Classic Horror")
	then
		ArrayList<String> options = new ArrayList();
		options.add("Some scientists hunt for a shark");
		options.add("A couple stumbles upon a strange town with no adults");
		String question = "Which topic?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "Jaws"
	when
		exists Question(question == "Which topic?", result == "Some scientists hunt for a shark")
	then
		GuiPopup p1 = new GuiPopup("You should watch Jaws", new ArrayList());
		p1.ask();
end;

rule "Children of the Corn"
	when
		exists Question(question == "Which topic?", result == "A couple stumbles upon a strange town with no adults")
	then
		GuiPopup p1 = new GuiPopup("You should watch Children of the Corn", new ArrayList());
		p1.ask();
end;

rule "Contemporary Horror"
	when
		exists Question(question == "What type?", result == "Contemporary Horror")
	then
		ArrayList<String> options = new ArrayList();
		options.add("A deaf-mute is trapped in her house by a masked killer");
		options.add("A spooky children's character comes to life and terrorises a mother");
		String question = "Which topic?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "Hush"
	when
		exists Question(question == "Which topic?", result == "A deaf-mute is trapped in her house by a masked killer")
	then
		GuiPopup p1 = new GuiPopup("You should watch Hush", new ArrayList());
		p1.ask();
end;

rule "Babadook"
	when
		exists Question(question == "Which topic?", result == "A spooky children's character comes to life and terrorises a mother")
	then
		GuiPopup p1 = new GuiPopup("You should watch The Babadook", new ArrayList());
		p1.ask();
end;

// ---------------------------------------------------------------------------------------------------------------------------------------------

rule "TV Show"
	when
		exists Question(question == "Movie or TV Show?", result == "TV Show");
	then
		ArrayList<String> options = new ArrayList();
		options.add("Drama");
		String question = "What genre?"; 
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "Drama TV Shows"
	when
		exists Question(question == "Movie or TV Show?", result == "TV Show");	
		exists Question(question == "What genre?", result == "Drama")
	then
		ArrayList<String> options = new ArrayList();
		options.add("Crime");
		String question = "What type?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "Crime TV Shows"
	when
		exists Question(question == "Movie or TV Show?", result == "TV Show");	
		exists Question(question == "What type?", result == "Crime")
	then
		ArrayList<String> options = new ArrayList();
		options.add("Good Guys");
		options.add("Bad Guys");
		String question = "What subtype?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;


rule "Good Guys"
	when
		exists Question(question == "Movie or TV Show?", result == "TV Show");	
		exists Question(question == "What subtype?", result == "Good Guys")
	then
		ArrayList<String> options = new ArrayList();
		options.add("Modern British Sherlock Holmes");
		options.add("FBI detectives tracking serial killers");
		String question = "Which topic?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "Sherlock"
	when
		exists Question(question == "Which topic?", result == "Modern British Sherlock Holmes");
	then
		GuiPopup p1 = new GuiPopup("You should watch Sherlock Holmes", new ArrayList<String>());
		p1.ask();
end;

rule "Criminal Minds"
	when
		exists Question(question == "Which topic?", result == "FBI detectives tracking serial killers");
	then
		GuiPopup p1 = new GuiPopup("You should watch Criminal Minds", new ArrayList<String>());
		p1.ask();
end;

rule "Bad Guys"
	when
		exists Question(question == "Movie or TV Show?", result == "TV Show");	
		exists Question(question == "What subtype?", result == "Bad Guys")
	then
		ArrayList<String> options = new ArrayList();
		options.add("Cartel");
		options.add("Biker Gang");
		options.add("Meth Cooks");
		String question = "Which topic?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "Cartel TV Show"
	when
		exists Question(question == "Which topic?", result == "Cartel");
	then
		GuiPopup p1 = new GuiPopup("You should watch Narcos", new ArrayList<String>());
		p1.ask();
end;

rule "Biker Gang TV Show"
	when
		exists Question(question == "Which topic?", result == "Biker Gang");
	then
		GuiPopup p1 = new GuiPopup("You should watch Sons fo Anarchy", new ArrayList<String>());
		p1.ask();
end;

rule "Meth Cooks TV Show"
	when
		exists Question(question == "Which topic?", result == "Meth Cooks");
	then
		GuiPopup p1 = new GuiPopup("You should watch Breaking Bad", new ArrayList<String>());
		p1.ask();
end;