package com.sample
 
// import com.sample.DroolsTest.Message;
import java.util.ArrayList;

declare enum statusType
HELLO(0),GOODBYE(1);
	type_: int
end

declare Question
	question: String
	answers: ArrayList
	result: String
end

rule "Init"
	when
	then
		ArrayList<String> options = new ArrayList();
		options.add("Movie");
		options.add("TV Show");
		String question = "Movie or TV Show?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

// ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

rule "Movie"
	when
		exists Question(question == "Movie or TV Show?", result == "Movie");	
	then
		ArrayList<String> options = new ArrayList();
		options.add("Timeless Classics");
		options.add("Action");
		options.add("Documentaries");
		options.add("Comedy");
		String question = "What genre?"; 
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

// ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

rule "Timeless Classics"
	when
		exists Question(question == "What genre?", result == "Timeless Classics")
	then
		ArrayList<String> options = new ArrayList();
		options.add("Scientists create a cannon to send them to the moon");
		options.add("A lawyer defends an innocent blac man in 1930's south");
		options.add("A German expressionist film where an upper class man leads the lower class in revolt");
		String question = "What topic?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;


rule "Cannon to moon"
	when
		exists Question(question == "What topic?", result == "Scientists create a cannon to send them to the moon");
	then
		GuiPopup p1 = new GuiPopup("You should watch A Trip to the Moon", new ArrayList<String>());
		p1.ask();
end;

rule "Lawyer"
	when
		exists Question(question == "What topic?", result == "A lawyer defends an innocent blac man in 1930's south");
	then
		GuiPopup p1 = new GuiPopup("You should watch To Kill a Mockingbird", new ArrayList<String>());
		p1.ask();
end;

rule "Metropolis"
	when
		exists Question(question == "What topic?", result == "A German expressionist film where an upper class man leads the lower class in revolt");
	then
		GuiPopup p1 = new GuiPopup("You should watch Matropolis", new ArrayList<String>());
		p1.ask();
end;

// ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

rule "Action Movie"
	when
		exists Question(question == "Movie or TV Show?", result == "Movie");	
		exists Question(question == "What genre?", result == "Action")
	then
		ArrayList<String> options = new ArrayList();
		options.add("Martial arts");
		options.add("Serious");
		options.add("Goofy");
		String question = "What type?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "Martial arts"
	when
		exists Question(question == "Movie or TV Show?", result == "Movie");	
		exists Question(question == "What type?", result == "Martial arts")
	then
		ArrayList<String> options = new ArrayList();
		options.add("Realistic");
		options.add("Tarantino directed revenge movie");
		options.add("Special effects out the wazoo");
		String question = "What topic?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "Way of dragon"
	when
		exists Question(question == "What topic?", result == "Realistic");
	then
		GuiPopup p1 = new GuiPopup("You should watch Way of the Dragon", new ArrayList<String>());
		p1.ask();
end;

rule "Kill Bill"
	when
		exists Question(question == "What topic?", result == "Tarantino directed revenge movie");
	then
		GuiPopup p1 = new GuiPopup("You should watch Kill Bill Vol.1 and Kill Bill Vol.2", new ArrayList<String>());
		p1.ask();
end;

rule "Five venoms"
	when
		exists Question(question == "What topic?", result == "Special effects out the wazoo");
	then
		GuiPopup p1 = new GuiPopup("You should watch The Five Venoms", new ArrayList<String>());
		p1.ask();
end;


rule "Serious Movie"
	when
		exists Question(question == "Movie or TV Show?", result == "Movie");	
		exists Question(question == "What type?", result == "Serious")
	then
		ArrayList<String> options = new ArrayList();
		options.add("Comic book based");
		options.add("Sci-fi");
		String question = "What subtype?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "Comic book based Movie"
	when
		exists Question(question == "What subtype?", result == "Comic book based");	 	
	then
		ArrayList<String> options = new ArrayList();
		options.add("Film Noir");
		options.add("Ron Perlman in a shit ton of makeup");
		String question = "What topic?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));	
end;

rule "Hellboy"
	when 
		exists Question(question == "What topic?", result == "Ron Perlman in a shit ton of makeup");	 	
	then
		GuiPopup p1 = new GuiPopup("You should watch Hellboy", new ArrayList<String>());
		p1.ask();
end;

rule "Sin city"
	when
 		exists Question(question == "What topic?", result == "Film Noir");	 	
	then
		GuiPopup p1 = new GuiPopup("You should watch Sin City", new ArrayList<String>());
		p1.ask();
end;

rule "Sci fi movie"
	when
		exists Question(question == "What subtype?", result == "Sci-fi");	 	
	then
		ArrayList<String> options = new ArrayList();
		options.add("Cyberpunk cop in a huge city");
		options.add("Asteroid apocalypse");
		String question = "What topic?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));	
end;

rule "Cyberpunk"
	when
 		exists Question(question == "What topic?", result == "Cyberpunk cop in a huge city");	 	
	then
		GuiPopup p1 = new GuiPopup("You should watch Judge Dredd", new ArrayList<String>());
		p1.ask();
end;

rule "Asteroid apocalypse"
	when
 		exists Question(question == "What topic?", result == "Asteroid apocalypse");	 	
	then
		GuiPopup p1 = new GuiPopup("You should watch Armageddon", new ArrayList<String>());
		p1.ask();
end;


rule "Goofy Movie"
	when
		exists Question(question == "Movie or TV Show?", result == "Movie");	
		exists Question(question == "What type?", result == "Goofy")
	then
		ArrayList<String> options = new ArrayList();
		options.add("British");
		options.add("Not British");
		String question = "What subtype?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "Hot fuzz"
	when
		exists Question(question == "Movie or TV Show?", result == "Movie");	
 		exists Question(question == "What subtype?", result == "British");	 	
	then
		GuiPopup p1 = new GuiPopup("You should watch Hot Fuzz", new ArrayList<String>());
		p1.ask();
end;

rule "Not British Movie"
	when
		exists Question(question == "Movie or TV Show?", result == "Movie");	
		exists Question(question == "What subtype?", result == "British");	 	
	then
		ArrayList<String> options = new ArrayList();
		options.add("Homage to 80's");
		options.add("Actually from the 80's");
		options.add("Tarantino directed movie about people killing Nazis");
		String question = "What topic?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));	
end;

rule "Kung fury"
	when
		exists Question(question == "What topic?", result == "Homage to 80's");
	then
		GuiPopup p1 = new GuiPopup("You should watch Kung Fury", new ArrayList<String>());
		p1.ask();
end;

rule "Big trouble in China"
	when
		exists Question(question == "What topic?", result == "Actually from the 80's");
	then
		GuiPopup p1 = new GuiPopup("You should watch Big Trouble in Little China", new ArrayList<String>());
		p1.ask();
end;

rule "Inglorious Bastards"
	when
		exists Question(question == "What topic?", result == "Tarantino directed movie about people killing Nazis");
	then
		GuiPopup p1 = new GuiPopup("You should watch Inglorious Bastards", new ArrayList<String>());
		p1.ask();
end;

// ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

rule "Documentaries"
	when
		exists Question(question == "What genre?", result == "Documentaries")
	then
		ArrayList<String> options = new ArrayList();
		options.add("An inside look into the amateur porn industry");
		options.add("Noam Chromsy looks at wealth inequality in America");
		options.add("A story of drug dealers in 1980's Florida");
		options.add("A study of German Expressionist cinema and fascism");
		String question = "What topic?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "Porn"
	when
		exists Question(question == "What topic?", result == "An inside look into the amateur porn industry");
	then
		GuiPopup p1 = new GuiPopup("You should watch Hot Girls Wanted", new ArrayList<String>());
		p1.ask();
end;

rule "Requiem"
	when
		exists Question(question == "What topic?", result == "Noam Chromsy looks at wealth inequality in America");
	then
		GuiPopup p1 = new GuiPopup("You should watch Requiem for the American Dream", new ArrayList<String>());
		p1.ask();
end; 

rule "Drugs"
	when
		exists Question(question == "What topic?", result == "A story of drug dealers in 1980's Florida");
	then
		GuiPopup p1 = new GuiPopup("You should watch Cocaine Cowboys", new ArrayList<String>());
		p1.ask();
end;

rule "German cinema"
	when
		exists Question(question == "What topic?", result == "A study of German Expressionist cinema and fascism");
	then
		GuiPopup p1 = new GuiPopup("You should watch From Caligari to Hitler", new ArrayList<String>());
		p1.ask();
end;

// ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

rule "Comedy"
	when
		exists Question(question == "Movie or TV Show?", result == "Movie") and
		exists Question(question == "What genre?", result == "Comedy")
	then
		ArrayList<String> options = new ArrayList();
		options.add("Coen Brothers");
		options.add("Tarantino");
		options.add("Animated");
		String question = "What type?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "Coen Brothers"
	when
		exists Question(question == "What type?", result == "Coen Brothers")
	then
		ArrayList<String> options = new ArrayList();
		options.add("Greatest thing to happen to this earth. Go buy it on Amazon");
		options.add("The Odyssey set in the depression era south");
		options.add("Minesotan banker tries to ransom his own wife");
		String question = "Choose the description";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "Lebowski"
	when
		exists Question(question == "Choose the description", result == "Greatest thing to happen to this earth. Go buy it on Amazon")
	then
		GuiPopup p1 = new GuiPopup("You should watch The Big Lebowski", new ArrayList());
		p1.ask();
end;

rule "Oh Brother, Where Art Thou"
	when
		exists Question(question == "Choose the description", result == "The Odyssey set in the depression era south");
	then
		GuiPopup p1 = new GuiPopup("You should watch Oh Brother, Where Art Thou", new ArrayList());
		p1.ask();
end;

rule "Fargo"
	when
		exists Question(question == "Choose the description", result == "Minesotan banker tries to ransom his own wife")
	then
		GuiPopup p1 = new GuiPopup("You should watch Fargo", new ArrayList());
		p1.ask();
end;

rule "Tarantino"
	when
		exists Question(question == "What type?", result == "Tarantino")
	then
		ArrayList<String> options = new ArrayList();
		options.add("Non-linear story about gangsters");
		String question = "What story?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "Pulp Fiction"
	when
		exists Question(question == "What story?", result == "Non-linear story about gangsters")
	then
		GuiPopup p1 = new GuiPopup("You should watch Pulp Fiction", new ArrayList());
		p1.ask();
end;

rule "Animated"
	when
		exists Question(question == "What type?", result == "Animated")
	then
		ArrayList<String> options = new ArrayList();
		options.add("Adorable and underrated");
		options.add("Semi-funny trash");
		String question = "Which type?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "Home"
	when
		exists Question(question == "Which type?", result == "Adorable and underrated")
	then
		GuiPopup p1 = new GuiPopup("You should watch Home", new ArrayList());
		p1.ask();
end;

rule "South Park"
	when
		exists Question(question == "Which type?", result == "Semi-funny trash")
	then
		GuiPopup p1 = new GuiPopup("You should watch South Park: Bigger, Longer and Uncut", new ArrayList());
		p1.ask();
end;

// ---------------------------------------------------------------------------------------------------------------------------------------------
rule "TV Show"
	when
		exists Question(question == "Movie or TV Show?", result == "TV Show");
	then
		ArrayList<String> options = new ArrayList();
		options.add("Drama");
		options.add("Comedy");
		String question = "What genre?"; 
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "Drama TV Shows"
	when
		exists Question(question == "Movie or TV Show?", result == "TV Show");	
		exists Question(question == "What genre?", result == "Drama")
	then
		ArrayList<String> options = new ArrayList();
		options.add("Crime");
		options.add("Mindfuckey");
		String question = "What type?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "Crime TV Shows"
	when
		exists Question(question == "Movie or TV Show?", result == "TV Show");	
		exists Question(question == "What type?", result == "Crime")
	then
		ArrayList<String> options = new ArrayList();
		options.add("Good Guys");
		options.add("Bad Guys");
		String question = "What subtype?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;


rule "Good Guys"
	when
		exists Question(question == "Movie or TV Show?", result == "TV Show");	
		exists Question(question == "What subtype?", result == "Good Guys")
	then
		ArrayList<String> options = new ArrayList();
		options.add("Modern British Sherlock Holmes");
		options.add("FBI detectives tracking serial killers");
		String question = "What topic?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "Sherlock"
	when
		exists Question(question == "What topic?", result == "Modern British Sherlock Holmes");
	then
		GuiPopup p1 = new GuiPopup("You should watch Sherlock Holmes", new ArrayList<String>());
		p1.ask();
end;

rule "Criminal Minds"
	when
		exists Question(question == "What topic?", result == "FBI detectives tracking serial killers");
	then
		GuiPopup p1 = new GuiPopup("You should watch Criminal Minds", new ArrayList<String>());
		p1.ask();
end;

rule "Bad Guys"
	when
		exists Question(question == "Movie or TV Show?", result == "TV Show");	
		exists Question(question == "What subtype?", result == "Bad Guys")
	then
		ArrayList<String> options = new ArrayList();
		options.add("Cartel");
		options.add("Biker Gang");
		options.add("Meth Cooks");
		String question = "What topic?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "Cartel TV Show"
	when
		exists Question(question == "What topic?", result == "Cartel");
	then
		GuiPopup p1 = new GuiPopup("You should watch Narcos", new ArrayList<String>());
		p1.ask();
end;

rule "Biker Gang TV Show"
	when
		exists Question(question == "What topic?", result == "Biker Gang");
	then
		GuiPopup p1 = new GuiPopup("You should watch Sons fo Anarchy", new ArrayList<String>());
		p1.ask();
end;

rule "Meth Cooks TV Show"
	when
		exists Question(question == "What topic?", result == "Meth Cooks");
	then
		GuiPopup p1 = new GuiPopup("You should watch Breaking Bad", new ArrayList<String>());
		p1.ask();
end;

rule "ComedyTV"
	when
		exists Question(question == "Movie or TV Show?", result == "TV Show") and
		exists Question(question == "What genre?", result == "Comedy")
	then
		ArrayList<String> options = new ArrayList();
		options.add("Animated");
		options.add("Live Action");
		String question = "What type?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "Live Action"
	when
		exists Question(question == "What type?" && result == "Live Action");
	then
		ArrayList<String> options = new ArrayList();
		options.add("Workplace comedy");
		options.add("Family based comedy");
		options.add("Friends hanging out");
		String question = "What topic?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "Workplace comedy"
	when
		exists Question(question == "What topic?", result == "Workplace comedy")
	then
		ArrayList<String> options = new ArrayList();
		options.add("American");
		options.add("British");
		String question = "What country?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "American"
	when
		exists Question(question == "What country?", result == "American")
	then
		ArrayList<String> options = new ArrayList();
		options.add("One man comedy writing team");
		options.add("Two best friends work at a hospital");
		options.add("Pub owners get caught in various antics");
		options.add("Local government");
		options.add("Relatable story of dysfunctional workplaces");
		String question = "What story?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "30 Rock"
	when
		exists Question(question == "What story?", result == "One man comedy writing team")
	then
		GuiPopup p1 = new GuiPopup("You should watch 30 Rock", new ArrayList());
		p1.ask();
end;

rule "Scrubs"
	when
		exists Question(question == "What story?", result == "Two best friends work at a hospital")
	then
		GuiPopup p1 = new GuiPopup("You should watch Scrubs", new ArrayList());
		p1.ask();
end;

rule "Sunny Philadelphia"
	when
		exists Question(question == "What story?", result == "Pub owners get caught in various antics")
	then
		GuiPopup p1 = new GuiPopup("You should watch It's Always Sunny in Philadelphia", new ArrayList());
		p1.ask();
end;

rule "Parks and Rec"
	when
		exists Question(question == "What story?", result == "Local government")
	then
		GuiPopup p1 = new GuiPopup("You should watch Parks and Rec", new ArrayList());
		p1.ask();
end;

rule "Office US"
	when
		exists Question(question == "What story?", result == "Relatable story of dysfunctional workplaces")
		exists Question(question == "What country?", result == "American")
	then
		GuiPopup p1 = new GuiPopup("You should watch The Office (US)", new ArrayList());
		p1.ask();
end;

rule "BritishTV"
	when
		exists Question(question == "What country?", result == "British")
	then
		ArrayList<String> options = new ArrayList();
		options.add("Relatable story of dysfunctional workplaces");
		options.add("Socially awkward IT specialists");
		String question = "What story?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "Office UK"
	when
		exists Question(question == "What country?", result == "British") and
		exists Question(question == "What story?", result == "Relatable story of dysfunctional workplaces")
	then
		GuiPopup p1 = new GuiPopup("You should watch The Office (UK)", new ArrayList());
		p1.ask();
end;

rule "IT Crowd"
	when
		exists Question(question == "What story?", result == "Socially awkward IT specialists")
	then
		GuiPopup p1 = new GuiPopup("You should watch The IT Crowd", new ArrayList());
		p1.ask();
end;

rule "Family based comedy"
	when
		exists Question(question == "What topic?", result == "Family based comedy")
	then
		ArrayList<String> options = new ArrayList();
		options.add("A suburban middle child growing up");
		options.add("A rich family deals with their wealth falling apart");
		String question = "What story?";
		GuiPopup p1 = new GuiPopup(question, options);		
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "Malcolm"
	when
		exists Question(question == "What story?", result == "A suburban middle child growing up")
	then
		GuiPopup p1 = new GuiPopup("You should watch Malcolm in the Middle", new ArrayList());
		p1.ask();
end;

rule "Arrested Development"
	when
		exists Question(question == "What story?", result == "A rich family deals with their wealth falling apart")
	then
		GuiPopup p1 = new GuiPopup("You should watch Arrested Developmend", new ArrayList());
		p1.ask();
end;

rule "Friends hanging out"
	when
		exists Question(question == "What topic?", result == "Friends hanging out")
	then
		ArrayList<String> options = new ArrayList();
		options.add("70's stoners");
		options.add("A man tells his children about his various youthful exploits");
		options.add("An ex-cult member goes to New York and tries to make it");
		String question = "What story?";
		GuiPopup p1 = new GuiPopup(question, options);
		String ans = p1.ask();
		insert(new Question(question, options, ans));
end;

rule "70's Show"
	when
		exists Question(question == "What story?", result == "70's stoners")
	then
		GuiPopup p1 = new GuiPopup("You should watch That 70's Show", new ArrayList());
		p1.ask();
end;

rule "How I Met Your Mother"
	when
		exists Question(question == "What story?", result == "A man tells his children about his various youthful exploits")
	then
		GuiPopup p1 = new GuiPopup("You should watch How I met Your Mother", new ArrayList());
		p1.ask();
end;

rule "Unbreakable Kimmy"
	when
		exists Question(question == "What story?", result == "An ex-cult member goes to New York and tries to make it")
	then
		GuiPopup p1 = new GuiPopup("You should watch Unbreakable Kimmy Schmidt", new ArrayList());
		p1.ask();
end;